// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRxqYEj5QNqrC-CY0k_BQBfroujGnNGY4',
    appId: '1:894153293535:web:59b638f8da17c59fa8336a',
    messagingSenderId: '894153293535',
    projectId: 'facebook-clone-1211',
    authDomain: 'facebook-clone-1211.firebaseapp.com',
    storageBucket: 'facebook-clone-1211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG1gw9YJgtZIsNXitXrXHBcjqipnvi-Vs',
    appId: '1:894153293535:android:66800e7fbd9268d5a8336a',
    messagingSenderId: '894153293535',
    projectId: 'facebook-clone-1211',
    storageBucket: 'facebook-clone-1211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF1_G__AaG6A6YGDsFZVyk0mczdzq06fQ',
    appId: '1:894153293535:ios:23898e8581b3a63fa8336a',
    messagingSenderId: '894153293535',
    projectId: 'facebook-clone-1211',
    storageBucket: 'facebook-clone-1211.appspot.com',
    iosBundleId: 'com.example.facebookClone',
  );
}
